name: tryit_vendor_app
description: Vendor App


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  flutterfire_ui: ^0.4.0+1
  email_validator: ^2.0.1
  image_picker: ^0.8.5
  csc_picker: ^0.2.6
  cloud_firestore: ^3.1.12
  firebase_storage: ^10.2.12
  path_provider: ^2.0.9
  flutter_easyloading: ^3.0.3
  cached_network_image: ^3.2.0
  provider: ^6.0.2
  intl: ^0.17.0
  flutter_slidable: ^1.2.0
  search_page: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/

