// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-7n136x9PaUVTBZ5nh_WCfTPGJFoz-LM',
    appId: '1:428937200324:web:ff7aa3469ef18c06aa3f91',
    messagingSenderId: '428937200324',
    projectId: 'try-it-customerapp',
    authDomain: 'try-it-customerapp.firebaseapp.com',
    storageBucket: 'try-it-customerapp.appspot.com',
    measurementId: 'G-JBWW8Y4HDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9bPMxb2aaMXSM3TNvVjOxYYwOPlyijus',
    appId: '1:428937200324:android:6fa093c3d7bd5431aa3f91',
    messagingSenderId: '428937200324',
    projectId: 'try-it-customerapp',
    storageBucket: 'try-it-customerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe36YKBqgzPJOhCoGT7Ih0v81Z6reLa7s',
    appId: '1:428937200324:ios:37a5e6876f60a6daaa3f91',
    messagingSenderId: '428937200324',
    projectId: 'try-it-customerapp',
    storageBucket: 'try-it-customerapp.appspot.com',
    androidClientId: '428937200324-63otsvhj7f24e8dvih81gcs0smkkss4i.apps.googleusercontent.com',
    iosClientId: '428937200324-dgj8b4vovvljb2fnv6cnjbtfpt6tsoss.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe36YKBqgzPJOhCoGT7Ih0v81Z6reLa7s',
    appId: '1:428937200324:ios:37a5e6876f60a6daaa3f91',
    messagingSenderId: '428937200324',
    projectId: 'try-it-customerapp',
    storageBucket: 'try-it-customerapp.appspot.com',
    androidClientId: '428937200324-63otsvhj7f24e8dvih81gcs0smkkss4i.apps.googleusercontent.com',
    iosClientId: '428937200324-dgj8b4vovvljb2fnv6cnjbtfpt6tsoss.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
